#!/usr/bin/env php
<?php

xdebug_break();
$files = array(
    __DIR__ . '/../../vendor/autoload.php',
    __DIR__ . '/../../../autoload.php',
    dirname(__DIR__) . '/vendor/autoload.php'
);

$found = false;

foreach ($files as $file) {
    if (file_exists($file)) {
        require $file;
        $found = true;
        break;
    }
}

if (!$found) {
    die(
      'You need to set up the project dependencies using the following commands:' . PHP_EOL .
      'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
      'php composer.phar install' . PHP_EOL
    );
}

#use ParaTest\UI\Text\PHPUnitTextUI;

#PHPUnitTextUI::main();

xdebug_break();
use RedTest\core\ApplicationAspectKernel as ApplicationAspectKernel;

$applicationAspectKernel = ApplicationAspectKernel::getInstance();
$applicationAspectKernel->init(array(
    'debug' => TRUE,
    'cacheDir' => __DIR__ . '/../tests/cache',
    'includePaths' => array(
	    __DIR__ . '/../tests/RedTest/tests',
    ),
));

use ParaTest\Console\ParaTestApplication;

$app = new ParaTestApplication();
$app->run();
